name: sppdn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Perluas jangkauan SDK agar lebih fleksibel

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  get: ^4.6.6 # PERBAIKAN: Versi stabil yang benar

  # Firebase - Versi stabil dan kompatibel
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1 # REKOMENDASI: Versi stabil terbaru
  flutter_launcher_icons: ^0.13.1 
  image_picker: ^1.1.2 # For picking images from gallery/camera
  http: ^1.2.1

  # Utilitas
  flutter_native_splash: ^2.4.0 # Sesuaikan dengan versi SDK, 2.4.0 lebih aman
  flutter_image_compress: ^2.2.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2 # Tambahkan path_provider yang mungkin terlewat
  photo_view: ^0.15.0
  get_storage: ^2.1.1
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  file_picker: ^8.0.7
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # PERBAIKAN: Versi stabil yang benar

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#FFFFFF"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/logo.png

flutter_launcher_icons:
  android: true  # This will use ic_launcher as the name
  ios: true
  image_path: "assets/eBLBC.png"
  min_sdk_android: 21
