// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSkRIHIYJfc4swBv_wtAUk9yoGwjPSRE',
    appId: '1:62687958094:web:113cda23ca02ea43fd1f1f',
    messagingSenderId: '62687958094',
    projectId: 'blbc-base',
    authDomain: 'blbc-base.firebaseapp.com',
    storageBucket: 'blbc-base.firebasestorage.app',
    measurementId: 'G-YQSEQG3HG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWna50DJOukY5NnP1YnIGYgvs1Q4dBwOM',
    appId: '1:62687958094:android:1907576e1bb76cbcfd1f1f',
    messagingSenderId: '62687958094',
    projectId: 'blbc-base',
    storageBucket: 'blbc-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLJT-laaG5_A5Om_TlgqE-RQ97TmzXydM',
    appId: '1:62687958094:ios:39a7fddbb63f00eafd1f1f',
    messagingSenderId: '62687958094',
    projectId: 'blbc-base',
    storageBucket: 'blbc-base.firebasestorage.app',
    iosClientId: '62687958094-c5phjgj3uakrq92f2u2k09gkqevlebbu.apps.googleusercontent.com',
    iosBundleId: 'com.blbc.go.id.blbc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLJT-laaG5_A5Om_TlgqE-RQ97TmzXydM',
    appId: '1:62687958094:ios:39a7fddbb63f00eafd1f1f',
    messagingSenderId: '62687958094',
    projectId: 'blbc-base',
    storageBucket: 'blbc-base.firebasestorage.app',
    iosClientId: '62687958094-c5phjgj3uakrq92f2u2k09gkqevlebbu.apps.googleusercontent.com',
    iosBundleId: 'com.blbc.go.id.blbc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRSkRIHIYJfc4swBv_wtAUk9yoGwjPSRE',
    appId: '1:62687958094:web:113cda23ca02ea43fd1f1f',
    messagingSenderId: '62687958094',
    projectId: 'blbc-base',
    authDomain: 'blbc-base.firebaseapp.com',
    storageBucket: 'blbc-base.firebasestorage.app',
    measurementId: 'G-YQSEQG3HG1',
  );
}
